# Generated by Django 2.2.6 on 2020-03-28 03:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taskapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=255)),
                ('tasktype', models.CharField(choices=[(taskapp.models.TaskType('daily'), 'daily'), (taskapp.models.TaskType('other'), 'other')], max_length=5)),
                ('taskentrydate', models.DateField(default=datetime.date.today)),
                ('taskdescription', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='taskapp.Category')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitytype', models.CharField(choices=[(taskapp.models.ActivityType('completed'), 'completed'), (taskapp.models.ActivityType('continuing'), 'continuing'), (taskapp.models.ActivityType('quitting'), 'quitting')], max_length=10)),
                ('activitydescription', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taskapp.Task')),
            ],
        ),
    ]
